// <auto-generated />
namespace StrimmDAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-beta1-20501")]
    public sealed partial class addNewChanges : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addNewChanges));
        
        string IMigrationMetadata.Id
        {
            get { return "201407021841026_addNewChanges"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
