using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.Serialization;
using System.Text;
using System.Threading.Tasks;

namespace Strimm.Model
{
    [DataContract]
    public class VideoTubePreviewClip : ModelBase
    {
        private int videoTubePreviewClipId;
        private int videoTubeId;
        private float duration;
        private string previewClipKey;
        private bool isAutoGenerated;
        private DateTime addedDateTime;

        [DataMember]
        public int VideoTubePreviewClipId
        {
            get
            {
                return this.videoTubePreviewClipId;
            }
            set
            {
                this.videoTubePreviewClipId = value;
            }
        }

        [DataMember]
        public int VideoTubeId
        {
            get
            {
                return this.videoTubeId;
            }
            set
            {
                this.videoTubeId = value;
            }
        }

        [DataMember]
        public float Duration
        {
            get
            {
                return this.duration;
            }
            set
            {
                this.duration = value;
            }
        }

        [DataMember]
        public string PreviewClipKey
        {
            get
            {
                return this.previewClipKey;
            }
            set
            {
                this.previewClipKey = value;
            }
        }

        [DataMember]
        public bool IsAutoGenerated
        {
            get
            {
                return this.isAutoGenerated;
            }
            set
            {
                this.isAutoGenerated = value;
            }
        }

        [DataMember]
        public DateTime AddedDateTime
        {
            get
            {
                return this.addedDateTime;
            }
            set
            {
                this.addedDateTime = value;
            }
        }
    }
}
