using System;
using System.Reflection;
using System.Runtime.InteropServices;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: AssemblyConfigurationAttribute("net-4.0.win32; release")]
[assembly: AssemblyProductAttribute("Quarz.NET 2.3 for .NET 4.0")]
[assembly: AssemblyDescriptionAttribute("Quartz Scheduling Framework for .NET")]
[assembly: AssemblyCopyrightAttribute("Copyright 2001-2014 Marko Lahma")]
[assembly: AssemblyTrademarkAttribute("Apache License, Version 2.0")]
[assembly: AssemblyCompanyAttribute("http://www.quartz-scheduler.net/")]
[assembly: AssemblyCultureAttribute("")]
[assembly: ComVisibleAttribute(false)]
[assembly: CLSCompliantAttribute(true)]
[assembly: AssemblyVersionAttribute("2.3.0.18")]
[assembly: AssemblyInformationalVersionAttribute("2.3.0.18 / b502e573c253ef35954545a0fdd3cb8a2f5b3bcf")]
[assembly: AssemblyDelaySignAttribute(false)]

